services:
  populate-laws:
    image: borkanie/populate-laws:latest
    volumes:
      - ../../../../../../wg-configs/:/etc/wireguard/configs:ro
    environment:
      DBName: ${DBName}
      DBUser: ${DBUser}
      DBPassword: ${DBPassword}
      DBServerAddress: ${DBServerAddress:-host.docker.internal}
      DBPort: ${DBPort:-5432}
      WG_CONFIGS_DIR: /etc/wireguard/configs
      PROXY_BIND: 127.0.0.1:25344
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
