name: CI/CD deploy Backend Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - Backend/**
    workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and push Docker image
    - name: Build and push Docker image
      run: |
        cd Backend/ParliamentMonitor/
        ls -a 
        IMAGE=borkanie/continousdemocracyapi:latest
        docker build \
          -t $IMAGE \
          .
        docker push $IMAGE
        
    # 4. Deploy to Docker
    - name: Deploy to 
      run: |
        IMAGE_NAME="borkanie/continousdemocracyapi"
        CONTAINER_NAME="continuous-democracies"
        HOST_PORT1=8080
        HOST_PORT2=8081
        CONTAINER_PORT1=8080
        CONTAINER_PORT2=8081

        echo "Pulling latest image $IMAGE_NAME..."
        docker pull $IMAGE_NAME

        if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
          echo "Stopping and removing existing container $CONTAINER_NAME..."
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
        fi

        echo "Starting new container $CONTAINER_NAME..."
        docker run -d \
          --name $CONTAINER_NAME \
          -p $HOST_PORT1:$CONTAINER_PORT1 \
          -p $HOST_PORT2:$CONTAINER_PORT2 \
          --restart unless-stopped \
          $IMAGE_NAME

        echo "Backend Deployment complete!"


