name: CI/CD to MicroK8s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and push Docker image
    - name: Navigate to docker file
      run: |
        cd Backend/ParliamentMonitor/ | pwd

    # 4. Build and push Docker image
    - name: Build and push Docker image
      run: |
        ls -a

    # 5. Build and push Docker image
    - name: Go back to base
      run: |
        cd ../../
    
    # 6. Configure kubectl (for MicroK8s cluster)
    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_FILE }}" > ~/.kube/config

    # 7. Deploy to MicroK8s
    - name: Deploy to MicroK8s
      run: |
        kubectl set image deployment/continuous-democracies app=borkanie/continousdemocracyapi:${{ github.sha }} --record
        kubectl rollout status deployment/continuous-democracies
