name: CI/CD to MicroK8s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and push Docker image
    - name: Build and push Docker image
      run: |
        cd Backend/ParliamentMonitor/
        ls -a 
        IMAGE=borkanie/continousdemocracyapi:latest
        docker build \
          -t $IMAGE \
          .
        docker push $IMAGE
        
    # 4. Deploy to MicroK8s
    - name: Deploy to MicroK8s
      run: |
        microk8s kubectl apply -f deployment.yaml
        microk8s kubectl set image deployment/continuous-democracies app=borkanie/continousdemocracyapi:${{ github.sha }}
        microk8s kubectl rollout status deployment/continuous-democracies

